### ISSUE TITLE
Window opens with incorrect size on dual screen setups

### ISSUE THREAD

**Issue by RiedleroD** [RiedleroD/DodgeToDrums#8]
confirmed in win10 by PythonCode

**Comment by RiedleroD** [comment]
pyglet detects screen size incorrectly on dual screen setups – this has only been confirmed for windows, but this also may be an existing issue under *nix systems.

**Comment by RiedleroD** [comment]
See [this SO comment](https://stackoverflow.com/questions/63105588/wrong-screen-size-in-pyglet-on-dual-screen-setups).

**Comment by pdamianik** [comment]
Found a possible solution:

Instead of getting the size directly from the sreen object, you can get the screens modes with `modes=screen.get_modes()` and the last one of the resulting modes should match the actual screens resolution `mode=modes[-1]`
